version: '3.7'

networks:
  currency-network:

services:
  naming-server:
    image: alico96/mp-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

  currency-exchange:
    image: alico96/mp-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      spring.rabbitmq.host: rabbitmq

  currency-conversion:
    image: alico96/mp-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      spring.rabbitmq.host: rabbitmq

  api-gateway:
    image: alico96/mp-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      spring.rabbitmq.host: rabbitmq